### ISSUE TITLE
Drop support for Fish<3.0.0

### ISSUE THREAD

**Issue by edouard-lopez** [rafaelrinaldi/pure#234]
See [Versions-Support-Strategy](https://github.com/rafaelrinaldi/pure/wiki/Versions-Support-Strategy) and #123

### Todo

* [x] remove tests for Fish<3.0.0
* [x] remove CI tests
* [x] remove badge in doc
