### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by rafaelrinaldi** [rafaelrinaldi/pure#74]
I think we're almost good to go on a `v2.0.0` release.

## Current checklist:

- [x] Vim mode support
- [x] Cleanup Travis configuration
- [ ] ~Async support (see #56)~ [postponed](https://github.com/rafaelrinaldi/pure/issues/74#issuecomment-453709771)
- [x] Better color customization options (see #69, #70)
- [x] Add tests for #63 (git status and git branch functions) and #96 
- [x] :warning: naming convention to harmonize configuration's variables (see #130) this is a breaking change!

---

I'd love to hear your thoughts on what we have right now and would also appreciate if someone can help with the pending items.

Hope you guys are doing well!

**Comment by nautilus28** [comment]
Hello,

Thank you all for an awesome plugin.

I have just upgraded to the latest version with Vim mode support. Is there any way to not showing the Vim mode indicator on the screen?

Thanks,
Canh

**Comment by rafaelrinaldi** [comment]
Hey @nautilus28, this is happening because you probably have Vim mode enabled by default. To disable it you can either remove `fish_vi_key_bindings` from your Fish configuration file or run `fish_default_key_bindings`.

**Comment by nautilus28** [comment]
@rafaelrinaldi Many thanks for getting back. What I want is to enable Vim mode by default, but not showing mode indicator on the terminal, is it possible?

**Comment by rafaelrinaldi** [comment]
This is not possible right now. We will show the indicators for vim mode at all times as of #58. I'm happy to accept a PR to get this in though.

**Comment by nautilus28** [comment]
@rafaelrinaldi okay, thanks. I will try to make it possible.

**Comment by edouard-lopez** [comment]
@rafaelrinaldi we should add some tests on `fish_prompt` and `pre_prompt` (which are a big and ugly functions :cry:)

**Comment by rafaelrinaldi** [comment]
@edouard-lopez I agree. We could do this after the v2 release though?

Many thanks for the hard work and getting the peding issues resolved. I feel like we're pretty much ready for a revamped version release, what do you think?

**Comment by edouard-lopez** [comment]
@rafaelrinaldi I'm not comfortable with tests as an after-thought. However, as there is plenty of "legacy" code I don't want to block the release, instead add tests little by little and release more frequently.

**Comment by edouard-lopez** [comment]
@rafaelrinaldi Work on `async` support has stale recently. 

I think we should postponed it to future version and release a `2.0.0` as we do have a bunch of new features that have been shipped, the code evolved a lot, is stable stable and tested. 
Plus we have `3.0.0` support :)

What do you think?

**Comment by schrodincat** [comment]
Seems reasonable to me. We are not using semantic versioning though?

**Comment by edouard-lopez** [comment]
@schrodincat cool
 yes we try to follow semver as much as possible,  but I introduced some breaking changes on the recent version as I rename some variables in conf.d/pure.fish.
While revamping the _README.md_ I realized we have some inconsistencies in the naming of variable. This would be nice to improve that before releasing `2.0.0`

(I will update with commit/pr reference)

**Comment by edouard-lopez** [comment]
I wrote a proposal convention for renaming variable in #130 if you want to chime in.

**Comment by rafaelrinaldi** [comment]
The roadmap looks good to me 👍  Having Git async support behind a feature flag definitely makes sense.
